security:
    encoders:
        App\Entity\Registration:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: App\Entity\Registration
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            switch_user: true
            form_login:
                login_path: login
                check_path: login
                username_parameter: login[email]
                password_parameter: login[password]

            logout:
                path:   /logout
                target: /
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/participants, roles: ROLE_USER }
        - { path: ^/officials, roles: ROLE_USER }
        - { path: ^/transports, roles: ROLE_USER }
        - { path: ^/registration/edit, roles: ROLE_USER }
        - { path: ^/registration/change_password, roles: ROLE_USER }
#        - { path: ^/profile, roles: ROLE_USER }