twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    # other stuff here
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']

    globals:
        #end_date: 'November 15, 2018 9:34'
        end_date: 'March 21, 2019 23:59'