twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    # other stuff here
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']

    globals:
        #end_date is when you last can enter competitors etc.
        end_date: 'March 21, 2019 23:59'
        #deadline is from when increased registration fee is charged.
        deadline: 'March 12, 2019 23:59'