#index:
#    path: /
#    controller: App\Controller\DefaultController::index
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: welcome
        permanent: true
logout:
    path: /logout